name: heywiki
version: 0.3
api-version: 1.13
main: org.wikiwizard.papermc.HeywikiPlugin
authors: [Heywiki]
description: Test project for minecraft PaperMC
website: https://github.com/heywiki/HeywikiMinecraftMod
commands:
    version:
        description: Shows the version
        usage: /version
    traceargs:
        description: Debug trace args
        usage: /traceargs arg1 arg2 ...
    die:
        description: Player dies
        usage: /die
    healthplease:
        description: Addes health of player +1
        usage: /healthplease
    mqttpub:
        description: will send mqtt message to server configured in config.yml
        usage: /mqttpub hello world! OR /mqttpub topic:heywiki/mytopic hello world!
    mqttconf:
        description: displays the mqtt config in plugin.yml
        usage: /mqttconf